<?php

class Interswitchcheckout_Message
{
    public static function message($code, $message)
    {
        $response = array();
        $response['response_code'] = $code;
        $response['response_message'] = $message;
        $response = json_encode($response);
        return $response;
    }
	
	public static function get_response_codes() {
			return array(
				'00'=>'Approved by Financial Institution'
				,'01'=>'Refer to Financial Institution'
				,'02'=>'Refer to Financial Institution, Special Condition'
				,'03'=>'Invalid Merchant'
				,'04'=>'Pick-up card'
				,'05'=>'Do Not Honor'
				,'06'=>'Error'
				,'07'=>'Pick-Up Card, Special Condition'
				,'08'=>'Honor with Identification'
				,'09'=>'Request in Progress'
				,'10'=>'Approved by Financial Institution, Partial'
				,'11'=>'Approved by Financial Institution, VIP'
				,'12'=>'Invalid Transaction'
				,'13'=>'Invalid Amount'
				,'14'=>'Invalid Card Number'
				,'15'=>'No Such Financial Institution'
				,'16'=>'Approved by Financial Institution, Update Track 3'
				,'17'=>'Customer Cancellation'
				,'18'=>'Customer Dispute'
				,'19'=>'Re-enter Transaction'
				,'20'=>'Invalid Response from Financial Institution'
				,'21'=>'No Action Taken by Financial Institution'
				,'22'=>'Suspected Malfunction'
				,'23'=>'Unacceptable Transaction Fee'
				,'24'=>'File Update not Supported'
				,'25'=>'Unable to Locate Record'
				,'26'=>'Duplicate Record'
				,'27'=>'File Update Field Edit Error'
				,'28'=>'File Update File Locked'
				,'29'=>'File Update Failed'
				,'30'=>'Format Error'
				,'31'=>'Bank Not Supported'
				,'32'=>'Completed Partially by Financial Institution'
				,'33'=>'Expired Card, Pick-Up'
				,'34'=>'Suspected Fraud, Pick-Up'
				,'35'=>'Contact Acquirer, Pick-Up'
				,'36'=>'Restricted Card, Pick-Up'
				,'37'=>'Call Acquirer Security, Pick-Up'
				,'38'=>'PIN Tries Exceeded, Pick-Up'
				,'39'=>'No Credit Account'
				,'40'=>'Function not Supported'
				,'41'=>'Lost Card, Pick-Up'
				,'42'=>'No Universal Account'
				,'43'=>'Stolen Card, Pick-Up'
				,'44'=>'No Investment Account'
				,'51'=>'Insufficient Funds'
				,'52'=>'No Check Account'
				,'53'=>'No Savings Account'
				,'54'=>'Expired Card'
				,'55'=>'Incorrect PIN'
				,'56'=>'No Card Record'
				,'57'=>'Transaction not permitted to Cardholder'
				,'58'=>'Transaction not permitted on Terminal'
				,'59'=>'Suspected Fraud'
				,'60'=>'Contact Acquirer'
				,'61'=>'Exceeds Withdrawal Limit'
				,'62'=>'Restricted Card'
				,'63'=>'Security Violation'
				,'64'=>'Original Amount Incorrect'
				,'65'=>'Exceeds withdrawal frequency'
				,'66'=>'Call Acquirer Security'
				,'67'=>'Hard Capture'
				,'68'=>'Response Received Too Late'
				,'75'=>'PIN tries exceeded'
				,'76'=>'Reserved for Future Postilion Use'
				,'77'=>'Intervene, Bank Approval Required'
				,'78'=>'Intervene, Bank Approval Required for Partial Amount'
				,'90'=>'Cut-off in Progress'
				,'91'=>'Issuer or Switch Inoperative'
				,'92'=>'Routing Error'
				,'93'=>'Violation of law'
				,'94'=>'Duplicate Transaction'
				,'95'=>'Reconcile Error'
				,'96'=>'System Malfunction'
				,'98'=>'Exceeds Cash Limit'
				,'A0'=>'Unexpected error'
				,'A4'=>'Transaction not permitted to card holder, via channels'
				,'Z0'=>'Transaction Status Unconfirmed'
				,'Z1'=>'Transaction Error'
				,'Z2'=>'Bank account error'
				,'Z3'=>'Bank collections account error'
				,'Z4'=>'Interface Integration Error'
				,'Z5'=>'Duplicate Reference Error'
				,'Z6'=>'Incomplete Transaction'
				,'Z7'=>'Transaction Split Pre-processing Error'
				,'Z8'=>'Invalid Card Number, via channels'
				,'Z9'=>'Transaction not permitted to card holder, via channels'
			);
		}
	
	
}